# Generated by Django 5.2.8 on 2026-04-17 05:04

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='LoincCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loinc_num', models.CharField(max_length=20, unique=True)),
                ('shortname', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.TextField(blank=True, null=True)),
                ('property', models.CharField(blank=True, max_length=50, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('scale_typ', models.CharField(blank=True, max_length=20, null=True)),
                ('method_typ', models.CharField(blank=True, help_text='Campo METHOD_TYP del CSV LOINC. Ej: Automated count, PCR, ELISA.', max_length=150, null=True, verbose_name='method')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propiedad', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('CUANTITATIVO', 'Cuantitativo'), ('CUALITATIVO', 'Cualitativo')], default='CUANTITATIVO', max_length=15)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('opciones_cualitativas', models.CharField(blank=True, max_length=500, null=True)),
                ('sincronizado', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['nombre_propiedad'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='LabApp.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('tipo_formato', models.CharField(choices=[('RESULTADOS', 'Resultados (Solo propiedades y valores)'), ('IMAGENES_RESULTADOS', 'Imágenes y Resultados')], default='RESULTADOS', max_length=50)),
                ('texto_justificado_default', models.TextField(blank=True, null=True)),
                ('sincronizado', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo_muestra', models.CharField(blank=True, help_text='Ej: Sangre total con EDTA, Suero, Orina de 24h', max_length=150, null=True, verbose_name='Tipo de muestra')),
                ('metodo', models.CharField(blank=True, help_text='Ej: Impedancia eléctrica y microscópica, Espectrofotometría', max_length=200, null=True, verbose_name='Método analítico')),
                ('loinc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_panel', to='LabApp.loinccode')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, help_text='Subtítulo de agrupación en el reporte. Ej: FÓRMULA ROJA, SERIE PLAQUETARIA', max_length=100, null=True, verbose_name='Serie / Sección')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de la propiedad DENTRO de su sección.')),
                ('orden_seccion', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición de la SECCIÓN en el reporte PDF. Ej: FÓRMULA ROJA=1, FÓRMULA BLANCA=2, SERIE PLAQUETARIA=3. Todas las propiedades de la misma sección deben tener el mismo valor.', verbose_name='Orden de sección')),
                ('loinc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LabApp.loinccode')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_propiedades', to='LabApp.plantilla')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_propiedades', to='LabApp.propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad de plantilla',
                'verbose_name_plural': 'Propiedades de plantilla',
                'ordering': ['orden_seccion', 'orden', 'propiedad__nombre_propiedad'],
                'unique_together': {('plantilla', 'propiedad')},
            },
        ),
        migrations.AddField(
            model_name='plantilla',
            name='propiedades',
            field=models.ManyToManyField(blank=True, related_name='plantillas', through='LabApp.PlantillaPropiedad', to='LabApp.propiedad'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('NORMAL', 'Normal'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador')], default='NORMAL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_abreviado', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula_profesional', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_ssg', models.CharField(blank=True, max_length=50, null=True)),
                ('universidad_egreso', models.CharField(blank=True, max_length=150, null=True)),
                ('firma_digital', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('laboratorios', models.ManyToManyField(blank=True, related_name='usuarios', to='LabApp.laboratorio')),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='responsable_sanitario_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs_bajo_cargo', to='LabApp.usuario'),
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('fecha_muestra', models.DateField(blank=True, null=True)),
                ('hora_toma', models.TimeField(blank=True, null=True)),
                ('hora_impresion', models.TimeField(blank=True, null=True)),
                ('tipo_muestra', models.CharField(blank=True, max_length=150, null=True)),
                ('metodo', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen_resultado1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('imagen_resultado2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabApp.paciente')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analisis', to='LabApp.plantilla')),
                ('propiedades_excluidas', models.ManyToManyField(blank=True, related_name='analisis_excluidos', to='LabApp.propiedad')),
                ('propiedades_extra', models.ManyToManyField(blank=True, related_name='analisis_extra', to='LabApp.propiedad')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LabApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IntervaloReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10, null=True)),
                ('edad_min_meses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edad_max_meses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('sincronizado', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='LabApp.propiedad')),
            ],
            options={
                'unique_together': {('propiedad', 'edad_min_meses', 'edad_max_meses', 'sexo')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_propiedad', models.CharField(blank=True, help_text='Se completa automáticamente desde la FK propiedad al guardar.', max_length=100, null=True, verbose_name='Nombre propiedad')),
                ('seccion', models.CharField(blank=True, help_text='Agrupación de la propiedad en el reporte PDF. Se hereda de PlantillaPropiedad para props de plantilla; se asigna manualmente para propiedades extra.', max_length=200, null=True, verbose_name='Serie / Sección')),
                ('orden_seccion', models.PositiveSmallIntegerField(default=9999, help_text='Orden de aparición de la sección en el PDF. Valor menor = aparece antes. Se hereda de PlantillaPropiedad o se asigna al crear el análisis.', verbose_name='Orden de sección')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='LabApp.analisis')),
                ('loinc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LabApp.loinccode')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='LabApp.propiedad')),
            ],
            options={
                'ordering': ['orden_seccion', 'nombre_propiedad'],
                'unique_together': {('analisis', 'propiedad')},
            },
        ),
    ]
