# Generated by Django 5.2.8 on 2026-03-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_laboratorios/')),
            ],
        ),
        migrations.CreateModel(
            name='LoincCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loinc_num', models.CharField(max_length=20, unique=True)),
                ('shortname', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.TextField(blank=True, null=True)),
                ('property', models.CharField(blank=True, max_length=50, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('scale_typ', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('tipo_formato', models.CharField(choices=[('RESULTADOS', 'Resultados (Solo propiedades y valores)'), ('IMAGENES_RESULTADOS', 'Imágenes y Resultados'), ('RECETA_JUSTIFICADA', 'Receta Justificada (Solo texto)')], default='RESULTADOS', max_length=50)),
                ('texto_justificado_default', models.TextField(blank=True, null=True)),
                ('sincronizado', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='LabApp.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('fecha_muestra', models.DateField(blank=True, null=True)),
                ('hora_toma', models.TimeField(blank=True, null=True)),
                ('hora_impresion', models.TimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabApp.paciente')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analisis', to='LabApp.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propiedad', models.CharField(max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('sincronizado', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('loinc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LabApp.loinccode')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='LabApp.plantilla')),
            ],
            options={
                'unique_together': {('plantilla', 'nombre_propiedad')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propiedad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_blob1', models.ImageField(blank=True, null=True, upload_to='resultados_imagenes/')),
                ('valor_blob2', models.ImageField(blank=True, null=True, upload_to='resultados_imagenes/')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='LabApp.analisis')),
                ('loinc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LabApp.loinccode')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('NORMAL', 'Normal'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador')], default='NORMAL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_abreviado', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula_profesional', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_ssg', models.CharField(blank=True, max_length=50, null=True)),
                ('universidad_egreso', models.CharField(blank=True, max_length=150, null=True)),
                ('firma_digital', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('laboratorios', models.ManyToManyField(blank=True, related_name='usuarios', to='LabApp.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='LabApp.analisis')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LabApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='responsable_sanitario_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs_bajo_cargo', to='LabApp.usuario'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LabApp.usuario'),
        ),
        migrations.CreateModel(
            name='IntervaloReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_edad', models.CharField(blank=True, choices=[('NINO', 'Niño'), ('ADULTO', 'Adulto'), ('ADULTO_MAYOR', 'Adulto Mayor')], max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10, null=True)),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('sincronizado', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='LabApp.propiedadplantilla')),
            ],
            options={
                'unique_together': {('propiedad', 'grupo_edad', 'sexo')},
            },
        ),
    ]
