# Generated by Django 5.2.8 on 2025-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervaloreferencia',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='intervaloreferencia',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedadplantilla',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propiedadplantilla',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='intervaloreferencia',
            unique_together={('propiedad', 'grupo_edad', 'sexo')},
        ),
        migrations.AlterUniqueTogether(
            name='propiedadplantilla',
            unique_together={('plantilla', 'nombre_propiedad')},
        ),
    ]
